export interface IncomeStream {
  id: string;
  title: string;
  description: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  potential: 'Low' | 'Medium' | 'High';
  timeToSetup: string;
  tools: string[];
  steps: string[];
}

export const INCOME_STREAMS: IncomeStream[] = [
  {
    id: 'ai-content-creation',
    title: 'AI-Powered Content Creation',
    description: 'Automate blog posts, social media, or YouTube scripts using LLMs and AI video tools.',
    difficulty: 'Easy',
    potential: 'Medium',
    timeToSetup: '1-2 weeks',
    tools: ['Gemini', 'Midjourney', 'Canva AI', 'InVideo'],
    steps: [
      'Identify a niche with high search volume.',
      'Use AI to generate a content calendar.',
      'Create content using AI writing and image tools.',
      'Automate posting using scheduling tools.',
      'Monetize through ads, affiliates, or sponsorships.'
    ]
  },
  {
    id: 'saas-micro',
    title: 'Micro-SaaS with AI',
    description: 'Build small, focused software tools that solve specific problems using AI APIs.',
    difficulty: 'Hard',
    potential: 'High',
    timeToSetup: '1-3 months',
    tools: ['React', 'Vite', 'Gemini API', 'Firebase'],
    steps: [
      'Find a repetitive task people pay for.',
      'Develop a simple wrapper around an AI model.',
      'Set up a subscription model.',
      'Market to specific communities (Reddit, IndieHackers).',
      'Automate customer support with AI bots.'
    ]
  },
  {
    id: 'ai-stock-trading',
    title: 'AI Trading Bots',
    description: 'Use automated algorithms to trade stocks or crypto based on technical analysis and sentiment.',
    difficulty: 'Hard',
    potential: 'High',
    timeToSetup: '2-4 weeks',
    tools: ['Python', 'Alpaca API', 'Sentiment Analysis Tools'],
    steps: [
      'Learn basic algorithmic trading principles.',
      'Use AI to analyze market sentiment from news/social media.',
      'Backtest your strategy with historical data.',
      'Deploy on a paper trading account first.',
      'Automate execution with a reliable API.'
    ]
  },
  {
    id: 'digital-products',
    title: 'AI-Generated Digital Products',
    description: 'Create and sell e-books, stock photos, or design templates generated by AI.',
    difficulty: 'Easy',
    potential: 'Medium',
    timeToSetup: '3-7 days',
    tools: ['Midjourney', 'Gemini', 'Gumroad', 'Etsy'],
    steps: [
      'Research trending digital products on Etsy or Creative Market.',
      'Generate high-quality assets using AI.',
      'Package them into bundles or templates.',
      'Set up a storefront on Gumroad or Etsy.',
      'Use AI for SEO-optimized product descriptions.'
    ]
  }
];
